### ISSUE TITLE
Video not showing up in windows

### ISSUE THREAD

**Issue by RJ722** [sepehr-laal/livecam#1]
First of all, there was some problem with getVersion method, and I couldn't get it right - so I hard coded the version in the code to - "1.11.1" (My current one!), and then everything goes fine - no errors and webcam is switched on!, but when i open the livecam UI, all I see is a blank screen.

Output:
![screenshot](https://cloud.githubusercontent.com/assets/15556382/22040782/0233deb8-dcb9-11e6-8850-6b5e470fb1a9.jpg)

I've created a [gist](https://gist.github.com/RJ722/37332d55a8b54a7a166b9fffff5cb43c) for my current file state, you might have a look.

**Comment by 3p3r** [comment]
Upgraded to 1.11.1 and I do see the white screen myself as well. `getVersion()` works as expected for me. This does not seem like an issue of livecam, gstreamer itself is unable to show the stream with the following pipeline:

`tcpclientsrc host=127.0.0.1 port=10000 ! jpegdec ! autovideoconvert ! autovideosink -vv`

1.11.1 is an unstable release, latest gstreamer stable is 1.10.2, which works correctly with livecam. You may want to file a bug with gstreamer.

**Comment by RJ722** [comment]
Thank You @sepehr-laal for pointing this out! :)

**Comment by beanilsson** [comment]
Just thought I'd drop by to say that I downgraded from version 1.14 to 1.6 on Win10 and got it to work. I don't know about the versions in between though.
