### ISSUE TITLE
Is anyone using this on the raspberry pi?

### ISSUE THREAD

**Issue by mark-hahn** [sepehr-laal/livecam#11]
Is anyone using this on the raspberry pi?  Should it work?

**Comment by 3p3r** [comment]
I have not used it on a RPi personally but I have successfully used it on a Vivo Stick loaded with Ubuntu and connected to a C920 webcam.

I don't see a reason why it would not work. GStreamer is available on RPi. Whatever camera you connect to you RPi, make sure it's available through v4linux (e.g. doing `stat /dev/video0` should not return `file not found`).
