### ISSUE TITLE
Showing empty screen in windows

### ISSUE THREAD

**Issue by asishap007** [sepehr-laal/livecam#7]
In windows 10  I have installed Gstreamer version(gstreamer-1.0-x86_64-1.14.0.1.msi) and tried to run this module. But it is getting it as empty. Terminal it is showing it as below 

Setting pipeline to PLAYING ...
New clock: GstSystemClock

Open http://127.0.0.1:11000/ in your browser!
WebCam server started!

It is working fine with linux machine.
Can you please help me, what is the issue over here.

**Comment by 3p3r** [comment]
I have not run this package on Windows for over a year now. I mainly use this on Linux. Try setting `GST_DEBUG` to various levels as [described here](https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gstreamer/html/gst-running.html). Perhaps an element is failing silently. Can't debug much without logs.

**Comment by asishap007** [comment]
Thanks sepehr-laal. Will try that.

Is this module can be used to stream multiple USB webcam in Linux environment ? 
I mean by creating a 2 new LiveCam object having  device property.

**Comment by asishap007** [comment]
Hi Sepehr,
This is the log, got when I enable Debug option

WARN              ksvideosrc gstksvideosrc.c:458:gst_ks_video_src_open_device:<ksvideosrc0> failed to create/open KsClock

Pipeline is live and does not need PREROLL ...
Setting pipeline to PLAYING ...

Open http://127.0.0.1:11000/ in your browser!
WebCam server started!
0:00:00.558287550  3912 0000000003F49480 WARN               videopool gstvideopool.c:219:video_buffer_pool_set_config:<videobufferpool1> no caps in config

I am new in Gstreamer side, so can pleas help me to figure it out ?

**Comment by 3p3r** [comment]
@asishap007 try looking for error messages. the warning logs you posted are harmless. You can see for [yourself here](https://github.com/GStreamer/gst-plugins-bad/blob/master/sys/winks/gstksvideosrc.c).
To answer your other question, yes you can stream multiple cameras if your hardware resources allows it. Just launch it in two separate processes and use `device-index` in the config object.

**Comment by StephaneBischoff** [comment]
Hi, I am also getting an empty img tag in the browser on Windows 10. @sepehr-laal any fix for this?

@asishap007 did you fix your issue? Can you post the result here for others ;).

```
LiveCam parameters: { broadcast_addr: '127.0.0.1',
  broadcast_port: 12000,
  ui_addr: '127.0.0.1',
  ui_port: 11000,
  gst_tcp_addr: '127.0.0.1',
  gst_tcp_port: 10000 }
GstLaunch found: C:\gstreamer2\1.0\x86_64\bin\gst-launch-1.0.exe
GStreamer version: 1.14.2
GStreamer pipeline: ksvideosrc ! decodebin ! videoscale ! video/x-raw,width=800,height=600 ! videobalance saturation=0.0 ! videoconvert ! jpegenc ! multipartmux  boundary="--videoboundary" ! tcpserversink host=127.0.0.1 port=10000
Setting pipeline to PAUSED ...

0:00:00.139835156  2104 0000000003243C80 WARN              ksvideosrc gstksvideosrc.c:458:gst_ks_video_src_open_device:<ksvideosrc0>
 failed to create/open KsClock

Pipeline is live and does not need PREROLL ...

0:00:00.171696095  2104 0000000003243E40 FIXME                default gstutils.c:3963:gst_pad_create_stream_id_internal:<ksvideosrc0:src> Creating random stream-id, consider implementing a deterministic way of creating a stream-id

Setting pipeline to PLAYING ...
New clock: GstSystemClock

Open http://127.0.0.1:11000/ in your browser!
WebCam server started!
0:00:00.544927722  2104 0000000003243E40 FIXME               basesink gstbasesink.c:3145:gst_base_sink_default_event:<tcpserversink0> stream-start event without group-id. Consider implementing group-id handling in the upstream elements
```

**Comment by 3p3r** [comment]
@StephaneBischoff I don't know what's the status of GStreamer on Windows these days. I am primarily a Linux dev. You are more than welcome to submit patches.
