### ISSUE TITLE
Stopping the Broadcast

### ISSUE THREAD

**Issue by jagsus** [sepehr-laal/livecam#9]
Is there a way to stop the broadcast?

**Comment by 3p3r** [comment]
FYI, I am rewriting this module from scratch with better code and more features but for the meantime there is no internal way in code to shut it down. What I used in the past is spawning Livecam as a ChildProcess and shutting the process down when I am done streaming.

**Comment by jagsus** [comment]
Uh nice. I'm looking forward to that.
Do you have some example code on how to span/stop livecam as child process? I've never worked with child processes.

**Comment by jagsus** [comment]
Forget that. I figured it out. But I have another question: How do I embed the video in an html file? Would i just put the UI in or use the Gstreamer Broadcast? (If gstreamer broadcast: How do I embed it? html video tag?)

**Comment by 3p3r** [comment]
the html to play back the broadcast is embedded in the module as well. you can find it here: https://github.com/sepehr-laal/livecam/blob/e229dee6efbfe58aba29fde82c79ccf008e08510/livecam.js#L327

if you want to host it separately, you need to replace `@WEBCAM_ADDR@` and `@WEBCAM_PORT@` yourself somehow.
